zuul:
  ignored-headers: Access-Control-Allow-Origin
  routes:
    user:
      sensitiveHeaders: Cookie,Set-Cookie
      path:
      serviceId: USERSERVICE
    device:
      sensitiveHeaders: Cookie,Set-Cookie
      #url: http://localhost:8081/v1/device
      serviceId: DEVICESERVICE
server:
  port: 9090

security:
  ouath2:
    resource:
      jwt:
        key-value: javainuse
logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: apigateway

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discv-alphamon.herokuapp.com/eureka/
  instance:
    hostname: gateway-alphamon.herokuapp.com
ribbon:
  ReadTimeout: 60000




   
 
